title: Pietro Ferrara
description: >-
  Pietro Ferrara is an associate professor in Computer Science at Ca' Foscari
  University of Venice, working on abstract interpretation-based static
  analysis for software security and reliability.
url: "https://pietroferrara.github.io"
author:
  name: Pietro Ferrara
  email: pietro.ferrara@unive.it

# Build settings
markdown: kramdown
future: true

exclude:
   - Gemfile
   - Gemfile.lock
   - README.md
   - script
